### ISSUE TITLE
Option to change the display prefix

### ISSUE THREAD

**Issue by josegonzalez** [flant/kubedog#108]
Rather than have the output be prefixed with `#`, I would like to indent the output by some arbitrary number of characters. This would make the output look much better when used as a step within a build pipeline in my case.

Would you take a PR to modify the display prefix when tracking rollouts?

**Comment by distorhead** [comment]
Hi, @josegonzalez !

Firstly, check out new release https://github.com/flant/kubedog/releases/tag/v0.3.0. It introduces so called multitracker. Multitracker is a rollout type tracker (it means it tracks resources till ready condition), it is capable of tracking multiple resources at the same time.

IMPORTANT:
* Users of rollout tracker encouraged to migrate to multitracker, because old rollout-trackers will not receive future support.
* Multitracker cli is a little bit "spartan", it is made in a minimal viable variant to access library functions using cli for users who needs it. Because cli is not our main priority in development (it requires some more developers resources), kubedog is firstly an library.
* Multitracker has different output format, without `# ` prefixes, but it uses some special symbols to improve appearance. See demo:

![Demo](https://raw.githubusercontent.com/flant/werf-demos/master/kubedog/kubedog-multitrack-cmd.gif).

# Option to indent output

As of option to add display prefix spaces: it is certainly acceptable to add such an option for kubedog multitrack cli.

Multitrack uses our another library called logboek: https://github.com/flant/logboek. I think we may add some ability to indent output into this library. Need some more time to think about this.

**Comment by josegonzalez** [comment]
The multi-track stuff seems interesting, though it would be nice to also have the old "event-based" update output for it as well, as that is a bit more compact and useful to show to users in an event stream.

For reference, I'm using kubedog to track kubernetes resource updates inside of Dokku, which is a sort of Heroku-like experience around docker container orchestration.

**Comment by distorhead** [comment]
Multitracker shows logs as rollout tracker does. And kubernetes-events will be shown only for resource that failed to give user more detailed info for debug.

**Comment by distorhead** [comment]
@josegonzalez  https://github.com/flant/kubedog/releases/tag/v0.3.1

`kubedog multitrack --output-prefix="        "`

**Comment by distorhead** [comment]
By the way, in the new release https://github.com/flant/kubedog/releases/tag/v0.3.2 there is an option called `ShowServiceMessages: true` to enable verbose output of resource kubernetes events and other service messages, which by default will only be shown in the case when resource has failed.
