### ISSUE TITLE
Kubernetes 1.16 support

### ISSUE THREAD

**Issue by donbeave** [flant/kubedog#141]
Hello, guys!

Love your product.

It looks like `kubedog` 0.3.3 doesn't support the latest version of Kubernetes 1.16.0, which was released 2 days ago.

I'm getting this error:

command:
```bash
kubedog rollout track deployment nginx-ingress-controller -n ingress-nginx
```

output:
```bash
E0921 00:01:45.823083   18836 reflector.go:131] pkg/mod/k8s.io/client-go@v0.0.0-20190411052641-7a6b4715b709/tools/cache/reflector.go:99: Failed to list *v1beta1.Deployment: the server could not find the requested resource
```

**Comment by distorhead** [comment]
Will fix this ASAP. Thanks!

**Comment by distorhead** [comment]
Fixed in the new release https://github.com/flant/kubedog/releases/tag/v0.3.4

Also, `kubedog rollout *` commands is deprecated to use. It is better to use new multitracker:

```
echo '{"Deployments":[{"ResourceName":"nginx-ingress-controller","Namespace":"ingress-nginx"}]}' | kubedog multitrack
```

It has much better output and handling of events, also supports multiple resources tracking at the same time.

https://github.com/flant/kubedog#multitracker-cli
